name: markdown_toolbar
description: A customizable toolbar to enhance your experience of writing Markdown in Flutter apps.
version: 0.3.2
repository: https://github.com/iakmds/markdown_toolbar


environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0